### ISSUE TITLE
PRÁCTICA 4 "MODELO DE NEGOCIOS"

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-yce#1]
[REPORTE DE PRÁCTICA._ 4 MODELO DE NEGOCIOS - EQUIPO YCE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-yce/files/12825723/REPORTE.DE.PRACTICA._.4.MODELO.DE.NEGOCIOS.-.EQUIPO.YCE.pdf)

**Comment by lucero012** [comment]
20/20
Excelente trabajo. Cumple con la rúbrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
